---
- name: plant ssh public keys
  hosts: hetzner
  user: root
  vars_files: 
    - /home/ansible/secvar/hetzner_vars.yml

  tasks: 
  - name: setup users
    authorized_key: 
      state: present
      user: "{{ ansible_user }}"
      key: "{{ ansible_phys_pubkey }}"

  - name: setup users
    authorized_key: 
      state: present
      user: "{{ personal_user }}"
      key: "{{ personal_phys_pubkey }}"


