---
- name: set right DNS servers, including our own internal
  hosts: hetzner

  tasks: 
  - name: edit nmcli entries
    nmcli: 
      conn_name: enp0s31f6
      type: ethernet
      dns4:
        - 192.168.122.1
        - 213.133.100.100
        - 213.133.98.98
        - 213.133.99.99 
      state: present
