---
- name: manage libvirt guests 
  user: ansible 
  hosts: baremetal
  vars:
      host_name: web

  tasks:
# not going to do xml_lookup just for a template, thank you. 
# going with 'command" module and virt-clone
    - name: create VM {{ host_name }} items by cloning image
      command: "virt-clone --original=rhel-image --name={{ host_name }} --auto-clone"

    - name: sysprep VM {{ host_name }} 
      command: "virt-sysprep -d {{ host_name }} --hostname {{ host_name }} --operations defaults" 

    - name: transfer/prep SSH public key or keys to be injected into the images. 
      copy: 
        src: /home/ansible/.ssh/id_rsa.pub
        dest: /home/ansible/addkey

    - name: sysprep VM plant keys {{ host_name }} items
      command: "virt-sysprep -d {{ host_name }} --ssh-inject ansible:file:/home/ansible/.ssh/id_rsa.pub --ssh-inject ansible:file:/home/ansible/addkey --selinux-relabel" 
    
    - name: set description to {{ host_name }} items
      command: "virsh desc {{ host_name }} --title {{ host_name }}"
    
    - name: start guest VM "{{ host_name }}"
      virt:
          name: "{{ host_name }}"
          state: running

    - name: allow DHCP/DNS to register
      pause:
        minutes: 1
    

