---
- name: move from DHCP to desired fix IP 
  hosts: all 
  
  tasks: 
  - name: prerequisit packages
    yum: 
      name: NetworkManager-glib
      state: present

  - name: set fix IP and reboot 
    nmcli:
      conn_name: eth0-static 
      ifname: eth0
      ip4: 192.168.122.120/24
      gw4: 192.168.122.1
      type: ethernet
      state: present
      dns4: 192.168.122.1  
    when: ansible_hostname == "ansible-h"

  - name: set fix IP and reboot 
    nmcli:
      conn_name: eth0-static 
      ifname: eth0
      ip4: 192.168.122.130/24
      gw4: 192.168.122.1
      type: ethernet
      state: present
      dns4: 192.168.122.1  
    when: ansible_hostname == "satellite-h"

  # ehhh this needed due to a bug in nmcli module: 
  # https://github.com/ansible/ansible/issues/36615
  - name: set the connection ip4.method to manual
    command: nmcli con modify eth0-static ipv4.method manual

  - name: setup hosts file entries
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
    with_items: 
      - "192.168.122.120 tower ansible-h"
      - "192.168.122.130 satellite satellite-h satellite-h.example.com satellite.example.com"
      - "192.168.122.140 zabbix zabbix-h"
      - "192.168.122.150 f5 f5-h"
      - "192.168.122.1 hetzner"

#  - name: start delayed reboot
#    reboot: 
#       pre_reboot_delay: 20
#       msg: Rebooted by Ansible to finalize/test network config change
#    async: 10
#    poll: 0

# okay, now don't look, this is fugly. 
#
  - name: enable new connection
    shell: sleep 3s ; nmcli con down eth0 ; nmcli con up eth0-static ; systemctl reboot
    async: 10
    poll: 0 

