    ansible_user: "{{ ansible_win_user }}"
    ansible_password: "{{ ansible_win_password }}"
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: basic
    project_name: web
    number_of_hosts: 2
    os_type: win
